version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  ui:
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - gateway
    links:
      - gateway
    environment:
      - GATEWAY_URI=http://gateway:8080
  gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - MONGO_URI=mongodb://mongo:27017/cloud
      - RABBIT_HOST=rabbitmq
  user-service:
    build:
      context: user-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mongo
    links:
      - rabbitmq
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/cloud
      - RABBIT_HOST=rabbitmq