version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
  user-service:
    build:
      context: ../user-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/user_service